/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 02 13:31:23 GMT 2019
 */

package p_1;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import p_1.Amit;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Amit_ESTest extends Amit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.doo(2654);
      assertEquals(7962, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.doo((-539));
      assertEquals((-1078), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Amit amit0 = new Amit();
      boolean boolean0 = amit0.isEven(200);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Amit amit0 = new Amit();
      boolean boolean0 = amit0.isEven(1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.doo(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.RTerror();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.hoo();
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.foo();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.boo();
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Amit amit0 = new Amit();
      int int0 = amit0.goo();
      assertEquals(0, int0);
  }
}
