/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 24 16:26:32 GMT 2020
 */

package p_1;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import p_1.Amit;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Amit_ESTest extends Amit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Amit amit0 = new Amit();
      amit0.doo((-3824));
      amit0.doo((-11472));
      amit0.doo((-11472));
      amit0.doo((-34416));
      amit0.doo((-3824));
      amit0.doo((-34416));
      amit0.doo((-103248));
      amit0.doo((-11472));
      amit0.doo((-34416));
      amit0.doo((-34416));
      amit0.doo((-103248));
      amit0.doo((-11472));
      amit0.doo((-11472));
      amit0.doo((-34416));
      amit0.doo((-3824));
      amit0.doo((-11472));
      amit0.doo((-309744));
      amit0.doo((-309744));
      amit0.doo((-11472));
      amit0.doo((-11472));
      amit0.doo((-309744));
      amit0.doo((-34416));
      amit0.doo((-309744));
      amit0.doo((-929232));
      amit0.doo((-3824));
      amit0.doo((-2787696));
      amit0.doo((-34416));
      amit0.doo((-103248));
      amit0.doo((-929232));
      amit0.doo((-309744));
      amit0.doo((-309744));
      amit0.doo((-34416));
      amit0.doo((-34416));
      amit0.doo((-34416));
      amit0.doo((-2787696));
      amit0.doo((-103248));
      amit0.doo((-3824));
      amit0.doo((-34416));
      amit0.doo((-929232));
      amit0.doo((-8363088));
      amit0.doo((-25089264));
  }
}
